// Arms Subsystem controls Neo 500 Arm motor w/ 100:1, Neo-550 elbow motor w/ 210:1
// started with RobotBuilder Version: 5.0
// copied code from Smart Motion Example
// 29-Jan-2023  rod

// ?????  how is AllowedErr set???
// is maxRPM used???
// added 4 relay conntrol to drive RGB LED light string.
//// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;

import edu.wpi.first.wpilibj2.command.SubsystemBase;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
// REV smartMax code copied from Alternate Encoder example  %rod
import com.revrobotics.RelativeEncoder;
import com.revrobotics.SparkMaxPIDController;
import com.revrobotics.CANSparkMax;
import com.revrobotics.CANSparkMaxLowLevel.MotorType;
import edu.wpi.first.wpilibj.DigitalOutput;
import edu.wpi.first.wpilibj.DriverStation;



/**
 *
 */
public class Arms extends SubsystemBase {
  private static final int ArmID1 = 30; // %r1
  private static final int ElbowID = 31; // %r1
  private static final int ArmRatio = 100; // neo 500 42 cpr. 100:1 MaxPlanetary
  private static final int ElbowRatio = 210; // neo 550 42 cpr. 210:1 VexPlanetary

  private CANSparkMax arm_motor;
  private SparkMaxPIDController pidArm;
  private RelativeEncoder arm_encoder;

  public double kP, kI, kD, kIz, kFF, kMaxOutput, kMinOutput, maxRPM, maxVel, minVel, maxAcc, allowedErr;

  // private CANSparkMax arm_motor2;
  private CANSparkMax elbow_motor;
  private SparkMaxPIDController pidElbow;
  private RelativeEncoder elbow_encoder;

  private DigitalOutput m_redLED; // relays 1-4
  private DigitalOutput m_greenLED;
  private DigitalOutput m_blueLED;
  private DigitalOutput m_relay4;
  
  public Arms() {
    // initialize SPARK MAX neo500 w/ 100:1
    arm_motor = new CANSparkMax(ArmID1, MotorType.kBrushless);
    arm_motor.restoreFactoryDefaults();
    pidArm = arm_motor.getPIDController();
    arm_encoder = arm_motor.getEncoder();
    // PID coefficients

    maxRPM = 5700; // ????????????????????????????

    // set PID coefficients
    pidArm.setP(0.00015); // proportional for Neo 500 arm
    pidArm.setI(0);
    pidArm.setD(0);
    pidArm.setIZone(0);
    pidArm.setFF(0);
    pidArm.setOutputRange(-1, 1);

    // set Motion Magic
    int smartMotionSlot = 0; // ????????????????????????????????
    pidArm.setSmartMotionMaxVelocity(4000, smartMotionSlot);
    pidArm.setSmartMotionMinOutputVelocity(0, smartMotionSlot);
    pidArm.setSmartMotionMaxAccel(2500, smartMotionSlot);
    pidArm.setSmartMotionAllowedClosedLoopError(allowedErr, smartMotionSlot); // ?????????????

    // Neo550 w/ 210:1
    elbow_motor = new CANSparkMax(ElbowID, MotorType.kBrushless);
    elbow_motor.restoreFactoryDefaults();
    elbow_motor.setSmartCurrentLimit( 30, 40);
    pidElbow = elbow_motor.getPIDController();
    elbow_encoder = elbow_motor.getEncoder();
    // set PID coefficients
    pidElbow.setP(0.00015); // proportional for Neo 550 arm
    pidElbow.setI(0.0000);
    pidElbow.setD(0);
    pidElbow.setIZone(0);
    pidElbow.setFF(0);
    pidElbow.setOutputRange(-1, 1);

    // set Motion Magic
    pidElbow.setSmartMotionMaxVelocity(10000, smartMotionSlot);
    pidElbow.setSmartMotionMinOutputVelocity(0, smartMotionSlot);
    pidElbow.setSmartMotionMaxAccel(10000, smartMotionSlot);
    pidElbow.setSmartMotionAllowedClosedLoopError(allowedErr, smartMotionSlot); // ?????????????

    // setup LED relays.  Controlled by DIO 0-3 
    m_redLED = new DigitalOutput(0);  // relays 1-4
    m_greenLED = new DigitalOutput(1);
    m_blueLED = new DigitalOutput(2);
    m_relay4 = new DigitalOutput(3);
    if (DriverStation.getAlliance() == DriverStation.Alliance.Red)
      m_redLED.set(true);
    else
      m_blueLED.set(true);
  }

  @Override
  public void periodic() {
    // This method will be called once per scheduler run

  }

  @Override
  public void simulationPeriodic() {
    // This method will be called once per scheduler run when in simulation

  }

  public void position(double armPose, double elbowPose) {
    // magic arm control
    pidArm.setReference(armPose, CANSparkMax.ControlType.kSmartMotion);

    SmartDashboard.putNumber("Arm Encoder", arm_encoder.getPosition());
    SmartDashboard.putNumber("Arm Current", arm_motor.getOutputCurrent());

    // elbow motor
    pidElbow.setReference(elbowPose, CANSparkMax.ControlType.kSmartMotion);

    SmartDashboard.putNumber("Elbow Encoder", elbow_encoder.getPosition());
    SmartDashboard.putNumber("Elbow Current", elbow_motor.getOutputCurrent());

  }

  public void drive(double armsSpeed, double elbowSpeed) {
    arm_motor.set(armsSpeed);
    elbow_motor.set(elbowSpeed);
  }

  public double getElbowPosition() {
    return elbow_encoder.getPosition();
  }

  public double getArmPosition() {
    return arm_encoder.getPosition();
  }

  public void setLEDRelays (boolean relay1,boolean relay2,
  boolean relay3,boolean relay4){
    m_redLED.set(relay1);  // red LED string
    m_greenLED.set(relay2);
    m_blueLED.set(relay3);
    m_relay4.set(relay4);
  }
  
}
